version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app-dev
    container_name: laravel-app
    ports:
      - "8000:80"      # Laravel
      - "5173:5173"    # Vite
    volumes:
      - ./:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules
      - ./storage:/var/www/html/storage
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
      - COMPOSER_ALLOW_SUPERUSER=1
    depends_on:
      - db
    command: /bin/bash -c "apache2-foreground"

  db:
    image: postgres:16
    container_name: pgsql-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
